#!/bin/bash

# Need to run following each time container rebooted
mkdir -p /root/.ssh
cp -pr /workspace/.ssh/* /root/.ssh
eval "$(ssh-agent -s)"
ssh-add /root/.ssh/id_rsa_github

ssh -T git@github.com
# user.email=26860048+RoboNater@users.noreply.github.com
git config --global user.email 26860048+RoboNater@users.noreply.github.com

git config --global user.name RoboNater
